// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucpjcnqjmgleyjamalgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjcGpjbnFqbWdsZXlqYW1hbGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3OTYxMTAsImV4cCI6MjA1MDM3MjExMH0.dAmd50cmt2BJ-7Fd8y9Aofiu9nhbfK3A5CkQoGW7A5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);